# To run: conda env create -f environment-lnx-cuda.yml
name: csna
channels:
    - conda-forge
dependencies:
    - python=3.6
    - pip
    - Pillow
    - ipython
    - matplotlib
    - numpy
    - pytorch 
    - torchvision